version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Asia/Kolkata
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: 'daily'