data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifiers.vedhavyas]
name = "Vedhavyas"
public_key = "66d2f79b2ec95e9ebe4511587ba104ed797756a4fb999bcdad3ccfd92ef96f61"

[[chains]]
name = "Subspace"
title = "Autonomys"
color = "#5870B3"
icon = "https://raw.githubusercontent.com/vedhavyas/metadata-portal/refs/heads/master/src/assets/icons/autonomys.svg"
rpc_endpoints = [
    "wss://rpc.mainnet.subspace.foundation/ws",
    "wss://rpc-0.mainnet.autonomys.xyz/ws"
]
testnet = false
verifier = "vedhavyas"

[[chains]]
name = "Subspace"
title = "Autonomys Taurus"
color = "#5870B3"
icon = "https://raw.githubusercontent.com/vedhavyas/metadata-portal/refs/heads/master/src/assets/icons/autonomys.svg"
rpc_endpoints = [
    "wss://rpc-0.taurus.subspace.network/ws",
    "wss://rpc-1.taurus.subspace.network/ws"
]
testnet = true
verifier = "vedhavyas"

[[chains]]
name = "subspace-evm-domain"
title = "Autonomys Taurus EVM"
color = "#5870B3"
icon = "https://raw.githubusercontent.com/vedhavyas/metadata-portal/refs/heads/master/src/assets/icons/autonomys.svg"
rpc_endpoints = [
    "wss://auto-evm.taurus.autonomys.xyz/ws"
]
testnet = true
verifier = "vedhavyas"
encryption = "ethereum"
