data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifiers.vedhavyas]
name = "Vedhavyas"
public_key = "66d2f79b2ec95e9ebe4511587ba104ed797756a4fb999bcdad3ccfd92ef96f61"

[[chains]]
name = "Autonomys"
empty_path = true
color = "#5870B3"
icon = "https://raw.githubusercontent.com/vedhavyas/autonomys-metadata/refs/heads/master/icons/autonomys.svg"
rpc_endpoints = [
    "wss://rpc.mainnet.subspace.foundation/ws",
]
testnet = false
verifier = "vedhavyas"

[[chains]]
name = "Chronos"
empty_path = true
color = "#5870B3"
icon = "https://raw.githubusercontent.com/vedhavyas/autonomys-metadata/refs/heads/master/icons/autonomys.svg"
rpc_endpoints = [
    "wss://rpc.chronos.autonomys.xyz/ws",
]
testnet = true
verifier = "vedhavyas"
