data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifiers.vedhavyas]
name = "Vedhavyas"
public_key = "66d2f79b2ec95e9ebe4511587ba104ed797756a4fb999bcdad3ccfd92ef96f61"

[[chains]]
name = "Autonomys"
title = "Autonomys"
color = "#5870B3"
icon = ""
rpc_endpoints = [
    "wss://rpc.mainnet.subspace.foundation/ws",
    "wss://rpc-0.mainnet.autonomys.xyz/ws"
]
testnet = false
verifier = "vedhavyas"

[[chains]]
name = "Autonomys Taurus"
title = "Autonomys Taurus"
color = "#5870B3"
icon = ""
rpc_endpoints = [
    "wss://rpc-0.taurus.subspace.network/ws",
    "wss://rpc-1.taurus.subspace.network/ws"
]
testnet = true
verifier = "vedhavyas"

[[chains]]
name = "Autonomys Taurus EVM"
title = "Autonomys Taurus EVM"
color = "#5870B3"
icon = ""
rpc_endpoints = [
    "wss://auto-evm.taurus.autonomys.xyz/ws"
]
testnet = true
verifier = "vedhavyas"
