name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: 🛎 Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run collector
        id: collect
        run: |
          cargo run --release -- collect
          exit_code=$?
          if [ $exit_code -eq 12 ]
          then
            exit 0
          fi
          exit $exit_code
        shell: bash {0}

      - uses: ./.github/workflows/deploy
        id: deploy
        if: success() || failure() && (steps.collect.outcome == 'failure')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
